name: integration-backend-tests

on: pull_request

jobs:
  integration-backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go to backend and run integration tests
        run: cd backend && npm install && npm run test:integration
