name: unit-backend-tests

on: pull_request

jobs:
  unit-backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go to backend and run unit tests
        run: cd backend && npm install && npm run test:unit
